Media3 guide
THEOplayer/documentation pull request #146
Opened 2024-10-22 09:46 UTC by hovig-theo

2024-10-22 11:25 UTC, MattiasBuelens requested changes

2024-10-22 11:25 UTC, MattiasBuelens commented on theoplayer/how-to-guides/android/media3/getting-started.mdx
> +<Intro />
This component doesn't exist. (I assume you copied this from #143, where it's an imported component to have the same introduction across Web and Android.)

Remove it, and write your own introduction inline. 😉

2024-10-22 11:25 UTC, MattiasBuelens commented on theoplayer/how-to-guides/android/media3/getting-started.mdx
> +By default, the Media3PlayerIntegration will play all type of sources except HESP & MILLICAST.
```suggestion
By default, the `Media3PlayerIntegration` will play all type of sources except HESP and Millicast.
```

2024-10-22 11:25 UTC, MattiasBuelens commented on theoplayer/how-to-guides/android/media3/getting-started.mdx
> +### Add the Media3 Integration to the player.
```suggestion
### Add the Media3 Integration to the player
```

2024-10-22 11:25 UTC, MattiasBuelens commented on theoplayer/how-to-guides/android/media3/getting-started.mdx
> +### Add the Media3 Integration dependency
Nit-pick: write "integration" in lowercase.
```suggestion
### Add the Media3 integration dependency
```
(This occurs a couple of times in this file.)

2024-10-22 13:54 UTC, MattiasBuelens commented on theoplayer/how-to-guides/android/media3/getting-started.mdx
> +By default, the `Media3PlayerIntegration` will play all types of sources except HESP and MILLICAST.
Almost! 😛 
```suggestion
By default, the `Media3PlayerIntegration` will play all types of sources except HESP and Millicast.
```

2024-10-23 06:45 UTC, MattiasBuelens approved these changes
LGTM.

Let's wait for the Millicast PR to land first, so the whole platform-specific how-to guide thingy works correctly. 😉

2024-10-23 09:07 UTC, GillesMoris-THEO commented
Wait to merge, reviewing

2024-10-23 09:46 UTC, MattiasBuelens commented on theoplayer/how-to-guides/android/media3/getting-started.mdx
> +- TextTrack.cues, TextTrack.activeCues and cue-related events are not yet supported. Although subtitles do render correctly to the screen, the content of these subtitles is not yet exposed through ou
```suggestion
- `TextTrack.cues`, `TextTrack.activeCues` and cue-related events are not yet supported. Although subtitles do render correctly to the screen, the content of these subtitles is not yet exposed through our API.
```

2024-10-23 14:19 UTC, MattiasBuelens approved these changes

2024-10-23 14:21 UTC, GillesMoris-THEO approved these changes

2024-10-23 14:22 UTC, merged